### PR TITLE
Starting equipment

### PR DESCRIPTION
**Pull request by Zattri**
Please review first pull request about controls before reviewing this one

Added starting gear and items into combat_classes csv to generate characters with different equipment when starting the game

### CODE REVIEW

**Comment by Zattri** [comment]
Might also want to put a new screen in to show starting equipment and items on the character creation menu. You can use the new properties on the character to get what they start with, both Equipment and Items - "StartingEquipment" and "StartingItems"

**Comment by kwoolter** [comment]
Yeah so the class view.CharacterView is what gets used on character creation AND when you press 'C' in game.  So if you added equipment to that it would be useful !!!!

**Comment by kwoolter** [comment]
You can put in the logic that does not allow you to equip a shield if you have a 2H weapon if u like.  Fighter.equip_item() is probably the best place for that.

**Comment by kwoolter** [comment]
Ok added starting equipment to character view

**Pull request merged**
